---
# This task installs uwsgi, then configures any apps that you have set up.
- include: install-pip.yml
  when: uwsgi_install_method == "pip"
- include: install-apt.yml
  when: uwsgi_install_method == "apt"
- include: install-source.yml
  when: uwsgi_install_method == "source"

- name: Add the uwsgi configuration files
  template: dest=/etc/uwsgi-emperor/emperor.ini
            src=etc/uwsgi-emperor/emperor.ini
            owner=root
            group=www-data

- name: Create apps folder
  file: state=directory
        path={{ uwsgi_vassals_path }}
        owner={{ ansible_ssh_user }}
        group={{ ansible_ssh_user }}

- name: Make sure uwsgi-emperor is running (and runs on boot)
  service: name=uwsgi-emperor state=started enabled=yes
